const Climate = () => {
  return (
    <div className=" bg-secondary px-4 py-8 md:px-12 text-whiteText flex flex-col gap-8 md:flex-row h-full">
      <div className=" text-center md:text-left flex flex-col gap-8 md:basis-[60%]">
        <h1 className=" font-semibold text-3xl ">UNAB and Climate Change</h1>
        <p className=" text-sm">
          UNAB's solar-powered solution provides clean, renewable energy for
          businesses and households and presents a sustainable alternative to
          fossil fuels. This is very important in combating the climate change
          issues we currently face in many parts, including Africa.
        </p>
        <p className=" text-sm">
          Every kilowatt of power generated through our solar solutions
          represents the power that would have otherwise been generated by
          burning fossil fuels that release CO2 and other greenhouse gases(gases
          that warm the atmosphere).
        </p>
        <p className=" text-sm">
          At UNAB, we collect this data to help us track our efforts towards
          reducing global warming in line with international climate change
          agreements like the Paris Agreement.
        </p>
      </div>
      <div className=" w-full aspect-[1/1] h-full md:w-[40%]">
        <img src="/climate.png" alt="" className=" w-full h-full" />
      </div>
    </div>
  );
};

export default Climate;
